- name: "Install and configure awscli and kubectl"
  hosts: "{{ target | default('nothing') }}"
  vars:
    ansible_user: ubuntu
  become: true
  pre_tasks:
    - name: Install aws-cli
      community.general.snap:
        name: aws-cli
        classic: yes
  
    - name: Download kubectl 1.23.6
      ansible.builtin.command: sudo curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.23.6/bin/linux/amd64/kubectl 

    - name: Install kubectl
      ansible.builtin.command: sudo mv kubectl /usr/local/bin/kubectl
    
    - name: chmod kubectl
      ansible.builtin.command: sudo chmod 0755 /usr/local/bin/kubectl
