- name: "Install and configure awscli and kubectl"
  hosts: "{{ target | default('nothing') }}"
  vars:
    ansible_user: ubuntu
  become: true
  tasks:
    - name: Install jq
      ansible.builtin.command: sudo apt install jq -y

    - name: Install aws-cli
      ansible.builtin.command: sudo snap install aws-cli --classic
  
    - name: Download kubectl 1.23.6
      ansible.builtin.command: sudo curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.23.6/bin/linux/amd64/kubectl 

    - name: Install kubectl
      ansible.builtin.command: sudo mv kubectl /usr/local/bin/kubectl
    
    - name: chmod kubectl
      ansible.builtin.command: sudo chmod 0755 /usr/local/bin/kubectl

    - name: Get PC Token
      ansible.builtin.command: sudo export pc_token=$(curl -s --location {{ pc_api_url }}/login/ --header 'Content-Type: application/json' --data '{"username":"'{{ pc_access_key }}'","password":"'{{ pc_secret_key }}'"}' |jq -r '.token')

